### ISSUE TITLE
Long string variables not completely visible

### ISSUE THREAD

**Issue by harrisonhjones** [particle-iot/particle-tinker-app-ios#11]
When viewing a device's cloud variables, if the variable's value is long you cannot view the entire value. There doesn't appear to be a way to view the full value. I suggest we allow the user to tap on the value to view it's full value in a popup or we place the variable's value below the variable name if the value is cut off (indicates by the three dots `...`).

**Comment by idokleinman** [comment]
I'm on it, expected for v2.1.
Did you experience any crashes in the data device inspector?

**Comment by harrisonhjones** [comment]
No but I haven't tested it much. This issue was prompted by a customer and I downloaded the app to confirm. Good job btw, the new app looks great.

**Comment by idokleinman** [comment]
Thank you

**Comment by idokleinman** [comment]
Tap a long (truncated) variable result and get:

![simulator screen shot sep 15 2016 5 24 08 pm](https://cloud.githubusercontent.com/assets/6490062/18571852/8f4ecade-7b6a-11e6-89f1-d7ff2bd54a14.png)

**Comment by harrisonhjones** [comment]
Looks great! When does this go live?

**Comment by idokleinman** [comment]
Once I collect enough feedback / fix crashes for 2.0 I'll publish 2.1.
Meanawhile if you send me your Apple ID I can add you to TestFlight beta program so you can have this new feature on your device right away

**Comment by harrisonhjones** [comment]
Tried this out this weekend. Looks great. My only gripe: It's a bit hard to determine where you are supposed to tap. Is there any better UI element to indicate to the user that the value can be tapped and more information viewed? Given our limit of cloud variables and functions I don't think it would be unreasonable to take up a bit more space per cloud variable/function if it makes operation easier or more intuitive.

**Comment by idokleinman** [comment]
The iOS-y way is to turn the variable result text to blue (button)..  Like the variable name. Do you think that'll help or create more confusion?

I'm kinda not worried about it because any user with a long string var that will get a "abcde..." result will naturally tap/touch it to see if he can scroll or whatnot and will get the popup. I agree not the best call to action but on the other hand I am not inclined to add another line to each variable cell in the table (like the functions that roll down for arguments).

I also added explanation about it to the tutorial which is displayed the first time you see the device inspector screen.

**Comment by harrisonhjones** [comment]
ohk. Sounds good then. Thanks for the quick turn-around on this!
