### ISSUE TITLE
Couple of build issues with commit c61f57c (August 24, 2016)

### ISSUE THREAD

**Issue by steven7gn** [particle-iot/particle-tinker-app-ios#8]
Hi Ido-   

When I downloaded the zip file to build, and did the following:

pod repo update
commented out paths in podspec to spark-sdk-io and spark-setup-ios
pod install
updated keys file copying over from template

I had the following 3 build errors that I noticed:
a) c.lightStatusAndNavBar was not defined -- commend out this line in DeviceListViewController.swift and WelcomeViewController.swift
b) There was no WriteKey defined in the call to the segment analytics in AppDelegate.Swift.  I just defined this variable as a string using my name, and it took that.  I'm not familiar with the segment analytics package (heck I'm still coming up a huge learning curve with Swift and objective c as it is!)  but assume that it uses this write key as a key to go look up statistics.

I was able to compile and run ok, but thought that this might be useful feedback or maybe you can help me correct my build process.

-Steve

**Comment by RaimundasSakalauskas** [comment]
Hello, thank you for the feedback. I'm closing this issue as being too old to be relevant. I am currently in the process of making this build again (there are issues with spark vs particle dependencies). Not sure if this is still relevant to you, but keys are not commited into git because of security reasons. Developers who clone the project and have permission to use those keys, should add them to their version of the project manually.
